/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:cd9026b7-a332-4ac9-8203-7edd89b0c70d",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_R35e533rK",
    "aws_user_pools_web_client_id": "5g4d8dv7a6u6lvflr5n659afre",
    "oauth": {}
};


export default awsmobile;
